Repository sipd-wok/war_of_kolors, pull requests merged in 2025-03, with the labels that each got.

#1 butangan ko docker
  Frontend/.dockerignore
  Frontend/Dockerfile
  Frontend/README.Docker.md
  Frontend/app/Menu/page.tsx
  Frontend/app/layout.tsx
  Frontend/components/MenuClient.tsx
  Frontend/compose.yaml
  Frontend/context/WalletContext.tsx
Labels: Review effort 3/5

#2 gn butangan ko na page para sa game
  Frontend/README.Docker.md
  Frontend/app/MainGame/page.tsx
  Frontend/app/page.tsx
  Frontend/components/MenuClient.tsx
  Frontend/components/NavBar.tsx
  Frontend/components/SendToken.tsx
  Frontend/components/WalletButton.tsx
  Frontend/utils/contract.ts
Labels: Review effort 3/5

#6 may linter kag github workflows
  .github/workflows/node.js.yml
  Frontend/app/page.tsx
  Frontend/components/WalletButton.tsx
  Frontend/jest.config.ts
  Frontend/package-lock.json
  Frontend/package.json
Labels: Review effort 3/5

#15 added characters rng
  Backend/server.ts
  Frontend/app/_game/_scenes/MainMenu.ts
  Frontend/app/_game/_scenes/Shop.ts
  Frontend/package-lock.json
  Frontend/public/assets/char_1.png
  Frontend/public/assets/char_10.png
  Frontend/public/assets/char_11.png
  Frontend/public/assets/char_12.png
  Frontend/public/assets/char_2.png
  Frontend/public/assets/char_3.png
  Frontend/public/assets/char_4.png
  Frontend/public/assets/char_5.png
  Frontend/public/assets/char_6.png
  Frontend/public/assets/char_7.png
  Frontend/public/assets/char_8.png
  Frontend/public/assets/char_9.png
Labels: Review effort 2/5

#21 characters and potions
  Frontend/app/_game/_scenes/Shop.ts
  Frontend/public/assets/bronzedoor.png
  Frontend/public/assets/char_67.png
  Frontend/public/assets/char_68.png
  Frontend/public/assets/char_69.png
  Frontend/public/assets/char_70.png
  Frontend/public/assets/char_71.png
  Frontend/public/assets/char_72.png
  Frontend/public/assets/char_73.png
  Frontend/public/assets/char_74.png
  Frontend/public/assets/char_75.png
  Frontend/public/assets/char_76.png
  Frontend/public/assets/char_77.png
  Frontend/public/assets/char_78.png
  Frontend/public/assets/char_79.png
  Frontend/public/assets/char_80.png
  Frontend/public/assets/char_81.png
  Frontend/public/assets/char_82.png
  Frontend/public/assets/char_83.png
  Frontend/public/assets/char_84.png
  Frontend/public/assets/char_85.png
  Frontend/public/assets/char_86.png
  Frontend/public/assets/char_87.png
  Frontend/public/assets/char_88.png
  Frontend/public/assets/char_89.png
  Frontend/public/assets/char_90.png
  Frontend/public/assets/char_91.png
  Frontend/public/assets/char_92.png
  Frontend/public/assets/char_93.png
  Frontend/public/assets/char_94.png
  Frontend/public/assets/char_95.png
  Frontend/public/assets/char_96.png
  Frontend/public/assets/golddoor.png
  Frontend/public/assets/potion.png
  Frontend/public/assets/silverdoor.png
Labels: Review effort 3/5

#24 added hppotion
  Frontend/app/_game/_scenes/Shop.ts
  Frontend/public/assets/healthPotion.png
Labels: Review effort 2/5

#27 ready to build na
  Backend/node_modules/.package-lock.json
  Backend/package-lock.json
  Backend/server.ts
  Frontend/app/_game/EventBus.ts
  Frontend/app/_game/_scenes/MainMenu.ts
  Frontend/app/_game/_scenes/Room.ts
  Frontend/app/_game/_scenes/RoomList.ts
  Frontend/app/_game/_scenes/Shop.ts
  Frontend/app/_game/_scenes/WaitingRoom.ts
  Frontend/app/transactions/nftTransactions.ts
  Frontend/app/transactions/walletProcesses.ts
  Frontend/components/CheckBalance.tsx
  Frontend/components/SendToken.tsx
  Frontend/components/ui/input.tsx
  Frontend/context/WalletContext.tsx
  Frontend/contracts/WokNFT.json
  Frontend/contracts/WokToken.json
  Frontend/cypress/integration/signIn.ts
  Frontend/package-lock.json
  Frontend/utils/nftcontract.ts
  Frontend/utils/tokencontract.ts
  README.md
Labels: Review effort 3/5

#28 added tailwind oxide
  Frontend/package-lock.json
  Frontend/package.json
Labels: Review effort 1/5

#31 added bgm
  Backend/server.ts
  Frontend/app/_game/_scenes/Room.ts
  Frontend/app/_game/_scenes/WaitingRoom.ts
Labels: Review effort 2/5

#46 Quickfixes added more attributes sa marketplace
  Frontend/app/_components/marketplace/MarketplaceComponent.tsx
Labels: Review effort 2/5

#47 token_id
  Frontend/app/_components/marketplace/MarketplaceComponent.tsx
Labels: Review effort 1/5

#48 added nft image sa marketplace
  Frontend/app/_components/marketplace/MarketplaceComponent.tsx
Labels: Review effort 2/5

#49 ready to be built
  Frontend/app/_components/marketplace/MarketplaceComponent.tsx
  Frontend/app/_game/PhaserGame.tsx
  Frontend/app/_game/_scenes/MainMenu.ts
  Frontend/app/api/requestWok/route.ts
  Frontend/app/api/wallet/NFT/route.ts
  Frontend/context/WalletContext.tsx
Labels: Review effort 3/5

#50 V0.2.0
  Backend/package-lock.json
  Backend/package.json
  Frontend/context/WalletContext.tsx
Labels: Review effort 2/5

#55 gn pa sync ko na ang player data sa watingroom pakadtu sa room
  Backend/server.ts
  Frontend/app/_game/_scenes/Room.ts
  Frontend/app/_game/_scenes/WaitingRoom.ts
Labels: Review effort 4/5
